name: GitHub Classroom Autograding
on: [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Autograding
        uses: education/autograding@v1
